### ISSUE TITLE
udev rules in AppImage

### ISSUE THREAD

**Issue by probonopd** [jolinux/AppImage-Sigrok-Cli#1]
> Für die Ansteuerung der jeweiligen Hardware sind Firmware und udev-rules in die entsprechenden Verzeichnisse zu kopieren!

For Arduino, I am using this as part of a custom `AppRun` start script which appears to be working for me, at least on Live ISOs (more testing on installed systems needed):

```
cat > /tmp/roothelper <<\EOoF                                                                                                                                                           
#!/bin/bash                                                                                                                                                                             
cat > /etc/udev/rules.d/50-arduino.rules <<\EOF                                                                                                                                         
SUBSYSTEM=="tty", KERNEL=="ttyUSB[0-9]*|ttyACM[0-9]*", GROUP="users", MODE="0666"                                                                                                       
EOF                                                                                                                                                                                     
udevadm trigger
EOoF
chmod a+x /tmp/roothelper

sudo true && sudo /tmp/roothelper
sudo true || pkexec --disable-internal-agent /tmp/roothelper || true

rm /tmp/roothelper
```

Intended behavior:
* On Live ISOs, it just becomes root, does its thing, without asking the user
* On installed systems, it asks the user for the root password

Maybe you can use something similar for this AppImage, so that users can simply start it and "it just works".

**Comment by jolinux** [comment]
Hallo,                                  
danke für die Info. Diese Art dem AppImage die rules fest mit zugeben hatte ich in einer deiner git-Diskussionen schon gesehen.
Ob es für sigrok-cli so gut ist glaube ich nicht.
Erklärung:
Sigrok hat eine Vielzahl an Hardware, und somit auch viele rules Einträge. Ich würde dann auch nur den heutigen Stand implementieren können.
Root-Zugang ist für beide Versionen notwendig
- ohne Root könnte ich sigrok-AppImage sogar auch ohne Hardware betreiben (mit *.sr-Dateien)
- Bei deiner Version kommt bei jedem AppImage-Start die Rootabfrage und dies finde ich schon recht lästig !  (müßte man, wenn es für den User bequem laufen soll noch eine Abfrage hinzunehmen ob die udev-rules schon installiert sind !)

Für ein Livesystem wie eine LIVE-ISO aber eine gute Sache, da dort alles mit gebracht wird ! Aber das Host-System leider dennoch verändert wird (außer /etc/ + /tmp/ ist Ram)! 

Grüße
Jörg
Ps.: ich bleibe bei deutsch 1. deine Location ist Germany -) und 2. ich wollte auch den nicht so englischfähigen Menschen (wie mich) mal ein deutsches Tutorial schenken!

**Comment by probonopd** [comment]
> müßte man, wenn es für den User bequem laufen soll noch eine Abfrage hinzunehmen ob die udev-rules schon installiert sind !

... stimmt

> Ps.: ich bleibe bei deutsch 1. deine Location ist Germany -) und 2. ich wollte auch den nicht so englischfähigen Menschen (wie mich) mal ein deutsches Tutorial schenken!

Alles klar! :-)
